src/demo_proj/demo_proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls",
                              namespace='home')),
]

src/demo_proj/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('home-template/', views.HomeView.as_view(), name='home'),
    path('list/', views.HomeListView.as_view(), name='list'),
    path('create-name/', views.create_name, name='create-name'),
    path('create/', views.HomeCreateView.as_view(), name='create'),
    path('ajax-submit/', views.ajax_post, name='ajax_post'),
    path('<str:name>/', views.HomeDetailView.as_view(), name='detail'),
]

src/demo_proj/home/models.py
from django.db import models

# Create your models here.


class HomePage(models.Model):
    name = models.CharField(max_length=60,primary_key=True,default="Salman")
    city = models.CharField(max_length=60,default="Banglore")
    pub_date = models.DateField()

    def __str__(self):
        return '%s--%s' % (self.city,self.pub_date)

src/demo_proj/home/forms.py
from django import forms
from .models import HomePage

class HomePageForm(forms.Form):
    name = forms.IntegerField(label='Full Name')


class HomeForm(forms.ModelForm):

    class Meta:
        model = HomePage
        fields = '__all__'

src/demo_proj/home/views.py
import json


from django.shortcuts import render
from django.http import HttpResponse

from django.views.generic import TemplateView, ListView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy
from django.utils import timezone

from .models import HomePage
from .forms import HomePageForm,HomeForm

# Create your views here.


def index(request):
    data = 'Hi there,'
    a = HomePage.objects.all()
    return HttpResponse(a)

class HomeView(TemplateView):
    template_name = "templateview.html"

    def get_context_data(self, *args, **kwargs):
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        # context = {}
        context['today'] = timezone.now()
        return context


class HomeListView(ListView):
    template_name = "index.html"
    model = HomePage
    # queryset = HomePage.objects.filter(name="Anjali")

    def get_queryset(self, *args, **kwargs):
        # a = super(HomeListView, self).get_context_data(*args, **kwargs)
        # context = {}
        a = HomePage.objects.all()
        return a
    #
    #
    # # def get_queryset(self):
    # #     # a = super(HomeListView.get_queryset)
    # #     return HomePage.objects.all()[:2]
    def get_context_data(self, *args, **kwargs):
        context = super(HomeListView, self).get_context_data(*args, **kwargs)
        # context = {}
        # context['static_objects'] = HomePage.objects.all()
        context['today'] = timezone.now()
        return context


class HomeDetailView(FormMixin,DetailView):
    template_name = "detail.html"
    model = HomePage
    form_class = HomeForm
    success_url = reverse_lazy('home:list')

    def get_object(self):
        return HomePage.objects.filter(name=self.kwargs['name'])[:1].get()
    #
    def get_context_data(self, *args, **kwargs):
        context = super(HomeDetailView, self).get_context_data(*args, **kwargs)
        context['static_objects'] = HomePage.objects.all()[:1].get()
        return context
    #
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            name = form.cleaned_data.get('name')
            city = form.cleaned_data.get('city')
            print(city)
            # possition_applied_for = form.cleaned_data.get('possition_applied_for')
            # mobile_number = form.cleaned_data.get('mobile_number')
            # date_of_birth = form.cleaned_data.get('date_of_birth')
            if HomePage.objects.filter(city=city).exists():
                form.add_error(None, "City Exist")
                return self.form_invalid(form)
                print("if")
            else:
                print("else")
                form.save()
                return self.form_valid(form)
            form.save()
        else:
            return self.form_invalid(form)

    # def form_valid(self, form):
        # self.obj = form.save()
        # email_id = form.cleaned_data.get('email_id')
        # full_name = form.cleaned_data.get('full_name')
        # resume = self.obj.resume
        # subject = 'Thank you for your application!'
        # admin_subject = 'Job applicant registered for ' + str(form.instance.possition_applied_for) + ' position'
        # from_email = 'info@embassyofficeparks.com'
        # # 'mansi.jain@webenza.com','divya.p@embassyofficeparks.com'
        # resume_urls = self.request.build_absolute_uri(form.instance.resume.url)
        # template_object = render_to_string("emails/careers-thank-you.html",
        #                                    {"object": form.instance})
        # admin_template_object = render_to_string("emails/careers-admin.html",
        #                                    {"object": form.instance, 'resume_urls':resume_urls})
        # # user email
        # # 'mansi.jain@webenza.com','divya.p@embassyofficeparks.com'
        # send_mail(admin_subject, admin_template_object,
        #           from_email, ['dheeraj@webenza.com','praveen@webenza.com'], resume=resume, fail_silently=False)
        # # admin email
        # send_mail(subject, template_object,
        #           from_email, [email_id], resume=None, fail_silently=False)
        # return super(HomeDetailView, self).form_valid(form)


def create_name(request):
    if request.method == 'POST':
        form = HomePageForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            return HttpResponseRedirect('/home/list')
    else:
        form = HomePageForm()
    return render(request, 'create_name.html', {'form': form})


class HomeCreateView(CreateView):
    model = HomePage
    fields = ['name','city','pub_date']
    template_name = 'create_name.html'
    success_url = '/'

def ajax_post(request):
    if request.method == 'GET':
        post_text = request.POST.get('name_id')
        response_data = 'Success'

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

src/demo_proj/assets/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1 style=""></h1>

  </body>
</html>

src/demo_proj/assets/templates/create_name.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Create Name Form</title>
  </head>
  <body>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

  </body>
</html>

src/demo_proj/assets/templates/detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>{{object.name}}</h1>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %}
              <div class="alert alert-danger">
                   <strong>{{ error|escape }}</strong>
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %}
      <input type="submit" name="" value="Submit">
    </form>
  </body>
</html>

src/demo_proj/assets/templates/home/homepage_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>List view</h1>
    {% for obj in object_list %}
      <li>{{obj.name}}</li>
      <li>{{obj.city}}</li>
      <li>{{obj.pub_date}}</li>
      <a href="{% url 'home:detail' name=obj.name %}">Link</a>
      <li>-----------------------</li>
    {% endfor %}
  </body>
</html>

src/demo_proj/assets/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Hi Good Morning</h1>
    {% for i in object_list %}
    <h1>{{i.name}} {{i.city}}</h1>
    {% endfor%}
    <h1>{{today}}</h1>
    <form method="post" id="ajax-form">
      {% csrf_token %}
      <input type="text" class="name_class" id = 'name' value="">
      <input type="submit" id="ajax-test" value="Submit">
    </form>
    <h1 id="message"></h1>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script type="text/javascript">
        $(document).ready(function() {
        $('#ajax-form').on('submit', function(event){
        event.preventDefault();
        var catid;
        catid = $(this).attr("name");
        $.ajax(
        {
            type:"GET",
            url: "/home/ajax-submit",
            data:{
                     name_id: catid
            },
            success: function( data )
            {
                $( '#message' ).text(data);
            }
         })
    });
    });
    </script>
  </body>
</html>

src/demo_proj/assets/templates/templateview.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Hi Good morning</h1>
    <h1>{{today}}</h1>

  </body>
</html>